/* ===================================================================
   sw.js — service worker (task E1, PWA shell)
   Cache-first offline shell for Mesa. Bump CACHE on every deploy that
   changes any shell file; the version string is the only thing that
   needs to change to invalidate old installs.
   =================================================================== */

/* GENERATED by tools/build-sw.js — do not edit by hand (run: node tools/build-sw.js) */
const CACHE = 'mesa-fbdf016d078d';
/* END GENERATED */

// The full app shell — everything needed to boot and run with zero network.
/* GENERATED by tools/build-sw.js — do not edit by hand (run: node tools/build-sw.js) */
const SHELL_FILES = [
  './',
  'index.html',
  'manifest.webmanifest',
  'css/mesa.css',
  'data/foods.js',
  'data/recipes.js',
  'data/validate.js',
  'js/app.js',
  'js/engine.js',
  'js/library.js',
  'js/log.js',
  'js/planner.js',
  'js/render.js',
  'js/state.js',
  'js/sync.js',
  'vendor/zxing-browser.min.js',
  'assets/ingredients/almonds.png',
  'assets/ingredients/apples.png',
  'assets/ingredients/asparagus.png',
  'assets/ingredients/aubergine.png',
  'assets/ingredients/avocado.png',
  'assets/ingredients/bacon.png',
  'assets/ingredients/balsamic-vinegar.png',
  'assets/ingredients/bananas.png',
  'assets/ingredients/barley.png',
  'assets/ingredients/basil.png',
  'assets/ingredients/beef-mince-lean.png',
  'assets/ingredients/bell-pepper.png',
  'assets/ingredients/blueberries.png',
  'assets/ingredients/brazil-nuts.png',
  'assets/ingredients/bresaola.png',
  'assets/ingredients/broccoli-courgette.png',
  'assets/ingredients/broccoli.png',
  'assets/ingredients/brownie.png',
  'assets/ingredients/butter.png',
  'assets/ingredients/cabbage.png',
  'assets/ingredients/cannellini-beans.png',
  'assets/ingredients/capers.png',
  'assets/ingredients/cappuccino-unsweetened.png',
  'assets/ingredients/carrot.png',
  'assets/ingredients/carrots.png',
  'assets/ingredients/cauliflower.png',
  'assets/ingredients/cavolo-nero.png',
  'assets/ingredients/cherry-tomatoes-cucumber.png',
  'assets/ingredients/cherry-tomatoes.png',
  'assets/ingredients/chia-seeds.png',
  'assets/ingredients/chicken-breast.png',
  'assets/ingredients/chicken-thigh.png',
  'assets/ingredients/chickpeas.png',
  'assets/ingredients/cinnamon.png',
  'assets/ingredients/clams.png',
  'assets/ingredients/coconut-milk.png',
  'assets/ingredients/cod.png',
  'assets/ingredients/cola.png',
  'assets/ingredients/cooked-lentils.png',
  'assets/ingredients/courgette.png',
  'assets/ingredients/couscous.png',
  'assets/ingredients/cucumber.png',
  'assets/ingredients/dark-chocolate-85.png',
  'assets/ingredients/default-food.png',
  'assets/ingredients/eggs.png',
  'assets/ingredients/escarole.png',
  'assets/ingredients/espresso-unsweetened.png',
  'assets/ingredients/farro-cooked.png',
  'assets/ingredients/fast-food-beef-burger.png',
  'assets/ingredients/fast-food-fries.png',
  'assets/ingredients/feta-cheese.png',
  'assets/ingredients/fruit-jam.png',
  'assets/ingredients/garlic.png',
  'assets/ingredients/gelato-chocolate.png',
  'assets/ingredients/gelato-crema.png',
  'assets/ingredients/gelato-stracciatella.png',
  'assets/ingredients/gelato-yogurt.png',
  'assets/ingredients/ginger.png',
  'assets/ingredients/gorgonzola.png',
  'assets/ingredients/granola.png',
  'assets/ingredients/greek-yogurt.png',
  'assets/ingredients/green-beans.png',
  'assets/ingredients/herbs-black-pepper.png',
  'assets/ingredients/honey.png',
  'assets/ingredients/lemon-juice.png',
  'assets/ingredients/lettuce.png',
  'assets/ingredients/maple-syrup.png',
  'assets/ingredients/mayonnaise.png',
  'assets/ingredients/milk.png',
  'assets/ingredients/mixed-berries.png',
  'assets/ingredients/mozzarella.png',
  'assets/ingredients/mushrooms.png',
  'assets/ingredients/mussels.png',
  'assets/ingredients/mustard.png',
  'assets/ingredients/nutella.png',
  'assets/ingredients/oats.png',
  'assets/ingredients/olive-oil-lemon-dressing.png',
  'assets/ingredients/olive-oil.png',
  'assets/ingredients/olives.png',
  'assets/ingredients/oranges.png',
  'assets/ingredients/pak-choy.png',
  'assets/ingredients/parmesan.png',
  'assets/ingredients/pasta-filo.png',
  'assets/ingredients/pasta.png',
  'assets/ingredients/peaches.png',
  'assets/ingredients/pears.png',
  'assets/ingredients/pecorino.png',
  'assets/ingredients/pizza-bianca.png',
  'assets/ingredients/pork-loin.png',
  'assets/ingredients/pork-sausage.png',
  'assets/ingredients/potatoes.png',
  'assets/ingredients/prawns.png',
  'assets/ingredients/prosciutto-cotto.png',
  'assets/ingredients/provola.png',
  'assets/ingredients/pumpkin-chia-seeds.png',
  'assets/ingredients/pumpkin-seeds.png',
  'assets/ingredients/pumpkin.png',
  'assets/ingredients/quinoa-dry.png',
  'assets/ingredients/red-onion.png',
  'assets/ingredients/rice.png',
  'assets/ingredients/ricotta.png',
  'assets/ingredients/robiola.png',
  'assets/ingredients/rocket-arugula.png',
  'assets/ingredients/rye-bread.png',
  'assets/ingredients/salmon-fillet.png',
  'assets/ingredients/scamorza.png',
  'assets/ingredients/skyr.png',
  'assets/ingredients/sole-fish.png',
  'assets/ingredients/soy-sauce.png',
  'assets/ingredients/speck.png',
  'assets/ingredients/spinach.png',
  'assets/ingredients/spring-rolls.png',
  'assets/ingredients/strawberries.png',
  'assets/ingredients/sugar.png',
  'assets/ingredients/sweet-potato.png',
  'assets/ingredients/tofu.png',
  'assets/ingredients/tuna-in-olive-oil.png',
  'assets/ingredients/tuna.png',
  'assets/ingredients/turkey-breast.png',
  'assets/ingredients/vanilla-cinnamon.png',
  'assets/ingredients/vanilla.png',
  'assets/ingredients/walnuts.png',
  'assets/ingredients/whey-protein-powder.png',
  'assets/ingredients/white-bread.png',
  'assets/ingredients/wholewheat-bread.png',
  'assets/ingredients/wild-strawberries.png',
  'assets/recipes/boiled-chicken-broth.png',
  'assets/recipes/breakfast-bowl.png',
  'assets/recipes/burrito.png',
  'assets/recipes/butter-chicken.png',
  'assets/recipes/chinese-dinner.png',
  'assets/recipes/citrus-roast-turkey.png',
  'assets/recipes/club-sandwich.png',
  'assets/recipes/cooked-vegetables.png',
  'assets/recipes/default-recipe.png',
  'assets/recipes/dessert-sweets.png',
  'assets/recipes/fast-food-menu.png',
  'assets/recipes/fish-main.png',
  'assets/recipes/french-toast.png',
  'assets/recipes/ice-cream.png',
  'assets/recipes/meat-main.png',
  'assets/recipes/onigiri.png',
  'assets/recipes/pancakes.png',
  'assets/recipes/pasta.png',
  'assets/recipes/ramen.png',
  'assets/recipes/salad.png',
  'assets/recipes/shakshuka.png',
  'assets/recipes/soup.png',
  'icons/icon-180.png',
  'icons/icon-192.png',
  'icons/icon-512-maskable.png',
  'icons/icon-512.png',
  'icons/icon-maskable.svg',
  'icons/icon.svg'
];
/* END GENERATED */

// No skipWaiting() here: the new worker parks in "waiting" until the page posts
// SKIP_WAITING (below), so activation + the controllerchange reload happen exactly
// once, driven by the page — never mid-session behind the user's back.
self.addEventListener('install', function(event){
  event.waitUntil(
    caches.open(CACHE)
      .then(function(cache){ return cache.addAll(SHELL_FILES); })
  );
});

self.addEventListener('activate', function(event){
  event.waitUntil(
    caches.keys()
      .then(function(keys){
        return Promise.all(
          keys.filter(function(key){ return key !== CACHE; })
              .map(function(key){ return caches.delete(key); })
        );
      })
      // claim() fires controllerchange on open pages; app.js reloads on that.
      // That is the single reload path — no client.navigate() here on top of it.
      .then(function(){ return self.clients.claim(); })
  );
});

self.addEventListener('message', function(event){
  if(event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', function(event){
  const req = event.request;

  // Only handle same-origin GETs — everything else (cross-origin, POST, etc.)
  // passes straight through untouched.
  if(req.method !== 'GET' || new URL(req.url).origin !== self.location.origin){
    return;
  }

  if(req.mode === 'navigate'){
    // Network-first, but NEVER cache.put the fetched HTML into the versioned cache: doing
    // so paired a freshly-deployed index.html with whatever JS/CSS happened to still be
    // pinned under the OLD CACHE version whenever a deploy forgot to bump CACHE, so
    // offline/flaky loads could serve mismatched HTML+JS. Falling back only to the
    // install-time cached index.html (put there once, atomically, by the install handler's
    // cache.addAll(SHELL_FILES) above) keeps the offline shell internally consistent by
    // construction — it can only ever pair with the JS/CSS cached in that same install.
    event.respondWith(
      fetch(req).catch(function(){
        return caches.match('index.html');
      })
    );
    return;
  }

  event.respondWith(
    caches.match(req).then(function(cached){
      if(cached) return cached;
      return fetch(req).then(function(res){
        // Only cache good, basic (same-origin) responses.
        if(res && res.ok && res.type === 'basic'){
          const copy = res.clone();
          caches.open(CACHE).then(function(cache){ cache.put(req, copy); });
        }
        return res;
      }).catch(function(){
        // Offline and not in cache (e.g. a route not in SHELL_FILES) —
        // fall back to the cached shell page so navigations still boot.
        if(req.mode === 'navigate') return caches.match('index.html');
        return undefined;
      });
    })
  );
});
