#!/usr/bin/env node
'use strict';

/*
 * tools/build-sw.js
 *
 * Regenerates the two GENERATED regions of app/sw.js:
 *   - SHELL_FILES: rediscovered fresh from disk every run, so an asset
 *     someone forgets to add to the list can no longer silently break
 *     offline support.
 *   - CACHE: a content hash over every shell file plus the hand-written
 *     parts of sw.js itself, so a forgotten manual version bump can no
 *     longer ship a stale app shell to installed clients.
 *
 * Zero dependencies — plain node (fs, path, crypto).
 * Usage: node tools/build-sw.js
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const APP_DIR = path.join(ROOT, 'app');
const SW_PATH = path.join(APP_DIR, 'sw.js');

const MARKER_START = '/* GENERATED by tools/build-sw.js — do not edit by hand (run: node tools/build-sw.js) */';
const MARKER_END = '/* END GENERATED */';

// List every regular file directly inside `relDir` (relative to app/),
// as `relDir/name` paths. Missing directories are skipped silently —
// e.g. vendor/ might be removed someday.
function listDir(relDir){
  const abs = path.join(APP_DIR, relDir);
  if(!fs.existsSync(abs)) return [];
  return fs.readdirSync(abs)
    .filter(function(name){ return fs.statSync(path.join(abs, name)).isFile(); })
    .map(function(name){ return relDir + '/' + name; });
}

function buildShellFiles(){
  // Shell code: the two root entry points + manifest, plus every file
  // under css/, js/, data/, vendor/ combined and sorted by relative path.
  const codeFiles = []
    .concat(listDir('css'))
    .concat(listDir('js'))
    .concat(listDir('data'))
    .concat(listDir('vendor'))
    .sort();
  const shellGroup = ['./', 'index.html', 'manifest.webmanifest'].concat(codeFiles);

  // Ingredient icons: every PNG under assets/ingredients/ (skip junk
  // such as .DS_Store).
  const assetsGroup = listDir('assets/ingredients')
    .filter(function(p){ return p.toLowerCase().endsWith('.png'); })
    .sort();

  // App icons: every file under icons/.
  const iconsGroup = listDir('icons').sort();

  return shellGroup.concat(assetsGroup, iconsGroup);
}

function readOldShellFiles(src){
  const m = src.match(/const SHELL_FILES = \[([\s\S]*?)\n\];/);
  if(!m) return [];
  return m[1].split('\n')
    .map(function(line){ return line.trim().replace(/,$/, ''); })
    .filter(Boolean)
    .map(function(line){
      const sm = line.match(/^'(.*)'$/);
      return sm ? sm[1] : null;
    })
    .filter(Boolean);
}

function readOldCache(src){
  const m = src.match(/const CACHE = '([^']*)';/);
  return m ? m[1] : null;
}

function renderShellFilesBlock(files){
  const lines = files.map(function(f){ return "  '" + f + "'"; });
  return 'const SHELL_FILES = [\n' + lines.join(',\n') + '\n];';
}

// Rewrite the two generated regions in `src`. Works whether or not the
// marker comments already exist:
//  - if markers are present, replace the content between them;
//  - otherwise (first run), locate the bare `const CACHE = ...;` line
//    and the bare `const SHELL_FILES = [...];` array and wrap them.
function regenerate(src, newCacheLine, newShellBlock){
  const blockRe = /\/\* GENERATED by tools\/build-sw\.js — do not edit by hand \(run: node tools\/build-sw\.js\) \*\/\n([\s\S]*?)\n\/\* END GENERATED \*\//g;
  let sawCache = false;
  let sawShell = false;

  let out = src.replace(blockRe, function(whole, inner){
    if(inner.indexOf('SHELL_FILES') !== -1){
      sawShell = true;
      return MARKER_START + '\n' + newShellBlock + '\n' + MARKER_END;
    }
    if(inner.indexOf('CACHE') !== -1){
      sawCache = true;
      return MARKER_START + '\n' + newCacheLine + '\n' + MARKER_END;
    }
    return whole; // unrecognized generated block — leave untouched
  });

  if(!sawCache){
    const before = out;
    out = out.replace(/const CACHE = '[^']*';/, function(){
      sawCache = true;
      return MARKER_START + '\n' + newCacheLine + '\n' + MARKER_END;
    });
    if(out === before && !sawCache){
      throw new Error('build-sw: could not locate a CACHE line to wrap');
    }
  }

  if(!sawShell){
    const before = out;
    out = out.replace(/const SHELL_FILES = \[[\s\S]*?\n\];/, function(){
      sawShell = true;
      return MARKER_START + '\n' + newShellBlock + '\n' + MARKER_END;
    });
    if(out === before && !sawShell){
      throw new Error('build-sw: could not locate a SHELL_FILES array to wrap');
    }
  }

  return out;
}

// Hash (path + raw bytes) of every shell file in `files`, in order,
// plus the given sw.js text (which must have its CACHE value already
// excluded so the hash never feeds back into itself).
function computeHash(files, swTextForHash){
  const hash = crypto.createHash('sha256');
  files.forEach(function(rel){
    hash.update(rel);
    if(rel !== './'){
      hash.update(fs.readFileSync(path.join(APP_DIR, rel)));
    }
  });
  hash.update(swTextForHash);
  return hash.digest('hex');
}

function main(){
  const original = fs.readFileSync(SW_PATH, 'utf8');
  const oldCache = readOldCache(original);
  const oldFiles = readOldShellFiles(original);

  const newFiles = buildShellFiles();
  const newShellBlock = renderShellFilesBlock(newFiles);

  // Build a version of sw.js with the new SHELL_FILES in place and the
  // CACHE value blanked to a fixed placeholder, so the hash depends only
  // on the shell files and the hand-written parts of sw.js — never on
  // its own output.
  const forHash = regenerate(original, "const CACHE = '';", newShellBlock);
  const hash = computeHash(newFiles, forHash);
  const newCache = 'mesa-' + hash.slice(0, 12);

  let updated = regenerate(original, "const CACHE = '" + newCache + "';", newShellBlock);

  // Normalize line endings to LF and ensure exactly one trailing newline,
  // matching the existing file style.
  updated = updated.replace(/\r\n/g, '\n').replace(/\n*$/, '\n');

  const unchanged = updated === original;
  if(!unchanged) fs.writeFileSync(SW_PATH, updated);

  const oldSet = new Set(oldFiles);
  const newSet = new Set(newFiles);
  const added = newFiles.filter(function(f){ return !oldSet.has(f); });
  const removed = oldFiles.filter(function(f){ return !newSet.has(f); });

  console.log('CACHE: ' + (oldCache || '(none)') + ' -> ' + (unchanged ? 'unchanged' : newCache));
  console.log('SHELL_FILES: ' + newFiles.length + ' files (was ' + oldFiles.length + ')');
  if(added.length){
    console.log('ADDED (' + added.length + '):');
    added.forEach(function(f){ console.log('  + ' + f); });
  }
  if(removed.length){
    console.log('REMOVED (' + removed.length + '):');
    removed.forEach(function(f){ console.log('  - ' + f); });
  }
  if(!added.length && !removed.length){
    console.log('No files added or removed.');
  }
}

main();
